"""Action model representing UI actions to be executed."""

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from .selector import Selector


class ActionType(str, Enum):
    """UI action types."""
    
    NAVIGATE = "NAVIGATE"
    CLICK = "CLICK"
    TYPE = "TYPE"
    WAIT = "WAIT"
    WAIT_FOR_VISIBLE = "WAIT_FOR_VISIBLE"
    ASSERT_VISIBLE = "ASSERT_VISIBLE"
    ASSERT_TEXT = "ASSERT_TEXT"
    SCREENSHOT = "SCREENSHOT"
    SCROLL = "SCROLL"
    SWITCH_TAB = "SWITCH_TAB"
    MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW"
    CLICK_CHECKBOX = "CLICK_CHECKBOX"
    CLOSE_TAB = "CLOSE_TAB"
    COMPLETE = "COMPLETE"  # Special type indicating test completion
    
    def __str__(self) -> str:
        return self.value


@dataclass
class Action:
    """
    Represents a UI action to be executed.
    
    Actions are generated by the ActionAgent based on test goals
    and executed by the ActionExecutor.
    
    Attributes:
        type: The type of action to perform
        selector: Optional selector for element location (not needed for NAVIGATE, WAIT)
        value: Optional value for the action (URL for NAVIGATE, text for TYPE, etc.)
    
    Examples:
        >>> # Navigate to URL
        >>> Action(type=ActionType.NAVIGATE, value="https://example.com")
        
        >>> # Click element
        >>> Action(type=ActionType.CLICK, selector=Selector(SelectorType.TEXT, "Submit"))
        
        >>> # Type text
        >>> Action(type=ActionType.TYPE, selector=Selector(SelectorType.CSS, "#username"), value="admin")
    """
    
    type: ActionType
    selector: Optional[Selector] = None
    value: Optional[str] = None
    
    def __str__(self) -> str:
        parts = [f"type={self.type}"]
        if self.selector:
            parts.append(f"selector={self.selector}")
        if self.value:
            # Mask if it looks like a secret
            display_value = "***" if self.value and ("password" in str(self.selector).lower() or "pwd" in str(self.selector).lower()) else self.value
            parts.append(f"value='{display_value}'")
        return f"Action({', '.join(parts)})"
    
    def __repr__(self) -> str:
        return self.__str__()
